<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>A Review of A Multivariate Approach to the Study of Orichalcum ingots from the Underwater Gela’s Archaeological Site</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Report_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Report_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Review of A Multivariate Approach to the Study of Orichalcum ingots from the Underwater Gela’s Archaeological Site</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Gaia Smith &amp; Alice Thompson</em></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p><strong>1.1 Significance of this archaeological find and Gela</strong></p>
<p>The historic Gela, in Sicily Italy has been a treasure trove of archaeological finds for generations. This ancient city was strategically positioned at the crux of major maritime trade routes, which made it a populous and successful trading port <span class="citation" data-cites="Angelucci2026">(<a href="#ref-Angelucci2026" role="doc-biblioref">Angelucci, 2026</a>)</span>. Consequently, ships looking to trade goods like pottery, metals, and grain have traveled, and sunk, around Gela for centuries.</p>
<p>A shipwreck off the coast continues to provide significant archaeological finds to this day. This discovery dates back to 1988 <span class="citation" data-cites="nuttersworldGelaWreck">(<a href="#ref-nuttersworldGelaWreck" role="doc-biblioref">Nutter, 2025</a>)</span>, where it was first stumbled upon by divers near Bulala beach. We are exploring one of the most significant finds from this wreck; A veritable hoard of the fabled metal, Orichalcum.</p>
<p>The discovery of 40 orichalcum ingots in 2017 was a monumental one. There had never been a discovery of this quantity in one place anywhere in the world. There was also evidence of consistent casting processes, with overall similarities suggesting a rudimentary mold production. This was likely a hole dug in the ground and molten alloy was poured in the indentation to solidify. The morphology of the found ingots suggested cast-diverse technologies.</p>
<p><strong>2.2 What is orichalcum?</strong></p>
<p>Orichalcum is defined as a copper alloy with zinc content as the principal components. A widely varying quantity of lead and tin among other trace elements are expected. There is no consistent proportion to the amount of copper and zinc found, but the overall composition and relative amounts of principal elemental components can be used to deduce the rough date and origin of a sample. The modern day equivalent is brass.</p>
<p><strong>2.3 Summary of Collection Techniques</strong></p>
<p>In the initial analysis of the orichalcum ingots, X-Ray Fluorescence (XRF) spectroscopy via a portable spectrometer <span class="citation" data-cites="Caponetti2017-sc">(<a href="#ref-Caponetti2017-sc" role="doc-biblioref">Caponetti, Armetta, Martino, et al., 2017</a>)</span> was used. The subject paper includes that data and further investigates the composition of each ingot using more invasive and refined elemental analysis.</p>
<p>For further testing, and the subject of this paper, <span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> chose to test elemental compositions using Inductively coupled plasma optical emission spectroscopy (ICP-OES) and Inductively coupled plasma optical emission spectroscopy (ICP-MS) of each of the 38 orichalcum ingots. ICP-OES was used to obtain measures for the primary elements above 1000 parts per million (PPM) while ICP-MS was used for the more difficult to measure trace elements below 1000 PPM. Both techniques are destructive and require the extraction of ~20mg of the ingots by drilling a micro-well into each ingot to obtain material for testing.</p>
<p><strong>2.4 Scope of This Multivariate Analysis</strong></p>
<p>This multivariate analysis includes manipulations of the data collected from the ICP-OES and ICP-MS chemometric analysis, it does not include the data about physical characteristics of the ingots or any correlation analysis of those variables.</p>
<p>We have chosen to reuse data because the orichalcum ingot archaeological find near Gela, Italy is a literally one of a kind find, we do not have the resources or the belief that it would be ethical to conduct excessive destructive testing on artifacts of the like that may never be found again. Therefore, we have used <span class="citation" data-cites="Caponetti2017-sc">Caponetti, Armetta, Martino, et al. (<a href="#ref-Caponetti2017-sc" role="doc-biblioref">2017</a>)</span> ICP-OES and ICP-MS data of 38 orichalcum ingots.</p>
<p>Our goal is to create and present a comprehensive, comprehensible, reproducible, and replicable multivariate analysis of the data obtained from chemometric elemental analysis of 38 orichalcum ingots to determine if there is coherent clustering between samples that are consistent with different distances and linkages.</p>
<p>We will be excluding the Cu/Zn ratio variable in the source table as we chose to analyse the linkage of all elements between each other, not between Cu/Zn ratios and other elements.</p>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">3. EDA</h2>
<p><strong>3.1 Analysing raw data</strong></p>
<p>We performed a simple summary of the data in table 1 and created a box plot to visualize the data. Something to note is that the elements Cu, Zn, Pb, and Fe are all in percentages, where as the concentrations of the other elements are in PPM (parts per a million). This immediately indicated that scaling was needed.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Figure 1: Main component and trace element concentrations obtained by ICP-OES &amp; ICP-MS techniques</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: right;">Cu</th>
<th style="text-align: right;">Zn</th>
<th style="text-align: right;">Pb</th>
<th style="text-align: right;">Fe</th>
<th style="text-align: right;">Ni</th>
<th style="text-align: right;">Ag</th>
<th style="text-align: right;">Sb</th>
<th style="text-align: right;">As</th>
<th style="text-align: right;">Co</th>
<th style="text-align: right;">Cd</th>
<th style="text-align: right;">Sn</th>
<th style="text-align: right;">Te</th>
<th style="text-align: right;">Bi</th>
<th style="text-align: right;">Mn</th>
<th style="text-align: right;">Li</th>
<th style="text-align: right;">Al</th>
<th style="text-align: right;">V</th>
<th style="text-align: right;">Cr</th>
<th style="text-align: right;">Rb</th>
<th style="text-align: right;">Sr</th>
<th style="text-align: right;">Ba</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">5.60</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">580</td>
<td style="text-align: right;">146.0</td>
<td style="text-align: right;">55.7</td>
<td style="text-align: right;">9.85</td>
<td style="text-align: right;">2.79</td>
<td style="text-align: right;">12.2</td>
<td style="text-align: right;">9.70</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">41.4</td>
<td style="text-align: right;">19.9</td>
<td style="text-align: right;">5.55</td>
<td style="text-align: right;">11.50</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">4.29</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">534</td>
<td style="text-align: right;">199.0</td>
<td style="text-align: right;">132.0</td>
<td style="text-align: right;">36.40</td>
<td style="text-align: right;">8.44</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">4.80</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">72.8</td>
<td style="text-align: right;">20.8</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">4.46</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S3</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">5.91</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">451</td>
<td style="text-align: right;">131.0</td>
<td style="text-align: right;">105.0</td>
<td style="text-align: right;">23.80</td>
<td style="text-align: right;">8.47</td>
<td style="text-align: right;">16.5</td>
<td style="text-align: right;">6.70</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">29.0</td>
<td style="text-align: right;">15.7</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">8.89</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">2.70</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">8.90</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">S4</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6.17</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">558</td>
<td style="text-align: right;">171.0</td>
<td style="text-align: right;">70.0</td>
<td style="text-align: right;">11.10</td>
<td style="text-align: right;">4.83</td>
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">9.34</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">60.7</td>
<td style="text-align: right;">23.2</td>
<td style="text-align: right;">6.16</td>
<td style="text-align: right;">13.80</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S5</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">513</td>
<td style="text-align: right;">156.0</td>
<td style="text-align: right;">67.0</td>
<td style="text-align: right;">14.50</td>
<td style="text-align: right;">6.49</td>
<td style="text-align: right;">5.3</td>
<td style="text-align: right;">7.69</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">58.7</td>
<td style="text-align: right;">23.3</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">11.60</td>
<td style="text-align: right;">4.38</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">0.45</td>
</tr>
<tr class="even">
<td style="text-align: left;">S6</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">6.51</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">579</td>
<td style="text-align: right;">159.0</td>
<td style="text-align: right;">60.3</td>
<td style="text-align: right;">8.32</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">9.6</td>
<td style="text-align: right;">8.54</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">61.4</td>
<td style="text-align: right;">15.7</td>
<td style="text-align: right;">2.12</td>
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S7</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6.45</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">559</td>
<td style="text-align: right;">130.0</td>
<td style="text-align: right;">107.0</td>
<td style="text-align: right;">211.00</td>
<td style="text-align: right;">3.37</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;">17.60</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">51.0</td>
<td style="text-align: right;">22.3</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">S8</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">6.13</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">548</td>
<td style="text-align: right;">160.0</td>
<td style="text-align: right;">75.4</td>
<td style="text-align: right;">9.66</td>
<td style="text-align: right;">3.19</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">6.98</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">58.5</td>
<td style="text-align: right;">23.7</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">13.30</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S9</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">482</td>
<td style="text-align: right;">159.0</td>
<td style="text-align: right;">109.0</td>
<td style="text-align: right;">24.20</td>
<td style="text-align: right;">5.28</td>
<td style="text-align: right;">30.5</td>
<td style="text-align: right;">3.92</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">91.3</td>
<td style="text-align: right;">23.7</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">8.40</td>
<td style="text-align: right;">2.70</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">S10</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">435</td>
<td style="text-align: right;">105.0</td>
<td style="text-align: right;">111.0</td>
<td style="text-align: right;">23.50</td>
<td style="text-align: right;">8.29</td>
<td style="text-align: right;">16.2</td>
<td style="text-align: right;">6.65</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">27.6</td>
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">6.77</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S11</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">5.93</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">525</td>
<td style="text-align: right;">138.0</td>
<td style="text-align: right;">53.2</td>
<td style="text-align: right;">15.10</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">8.29</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">54.5</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">6.57</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">S12</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">6.67</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">141.0</td>
<td style="text-align: right;">50.1</td>
<td style="text-align: right;">13.80</td>
<td style="text-align: right;">4.45</td>
<td style="text-align: right;">8.3</td>
<td style="text-align: right;">8.14</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">55.0</td>
<td style="text-align: right;">13.4</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">3.13</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S13</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">458</td>
<td style="text-align: right;">189.0</td>
<td style="text-align: right;">549.0</td>
<td style="text-align: right;">197.00</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">17.3</td>
<td style="text-align: right;">38.30</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">181.0</td>
<td style="text-align: right;">86.6</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">9.28</td>
<td style="text-align: right;">3.08</td>
<td style="text-align: right;">2.23</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">1.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">S14</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">433</td>
<td style="text-align: right;">81.7</td>
<td style="text-align: right;">88.2</td>
<td style="text-align: right;">14.60</td>
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">20.3</td>
<td style="text-align: right;">1.98</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">26.1</td>
<td style="text-align: right;">29.7</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">6.51</td>
<td style="text-align: right;">2.49</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S15</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">5.20</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">549</td>
<td style="text-align: right;">171.0</td>
<td style="text-align: right;">107.0</td>
<td style="text-align: right;">20.60</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">23.4</td>
<td style="text-align: right;">4.24</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">92.0</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">3.44</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">S16</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">560</td>
<td style="text-align: right;">162.0</td>
<td style="text-align: right;">103.0</td>
<td style="text-align: right;">19.90</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">22.2</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">82.1</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">21.20</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">2.53</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S17</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6.92</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">177.0</td>
<td style="text-align: right;">153.0</td>
<td style="text-align: right;">54.70</td>
<td style="text-align: right;">9.06</td>
<td style="text-align: right;">31.8</td>
<td style="text-align: right;">65.80</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">27.9</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.31</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">7.27</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">S18</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">4.57</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">515</td>
<td style="text-align: right;">158.0</td>
<td style="text-align: right;">111.0</td>
<td style="text-align: right;">22.10</td>
<td style="text-align: right;">5.09</td>
<td style="text-align: right;">28.4</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">89.3</td>
<td style="text-align: right;">21.5</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">4.08</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">11.80</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S19</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">5.25</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">494</td>
<td style="text-align: right;">114.0</td>
<td style="text-align: right;">101.0</td>
<td style="text-align: right;">38.10</td>
<td style="text-align: right;">6.14</td>
<td style="text-align: right;">18.5</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">33.6</td>
<td style="text-align: right;">17.7</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">8.36</td>
<td style="text-align: right;">2.61</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: right;">3.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">S20</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">6.31</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">535</td>
<td style="text-align: right;">139.0</td>
<td style="text-align: right;">51.5</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">8.2</td>
<td style="text-align: right;">8.11</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">56.3</td>
<td style="text-align: right;">13.4</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">2.91</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S21</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">423</td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">68.0</td>
<td style="text-align: right;">14.40</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">25.3</td>
<td style="text-align: right;">26.3</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">2.49</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">S22</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">606</td>
<td style="text-align: right;">142.0</td>
<td style="text-align: right;">175.0</td>
<td style="text-align: right;">55.30</td>
<td style="text-align: right;">15.03</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">46.3</td>
<td style="text-align: right;">25.7</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">11.60</td>
<td style="text-align: right;">2.82</td>
<td style="text-align: right;">2.19</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">15.10</td>
<td style="text-align: right;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S23</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">623</td>
<td style="text-align: right;">121.0</td>
<td style="text-align: right;">67.2</td>
<td style="text-align: right;">9.12</td>
<td style="text-align: right;">2.61</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;">9.07</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">40.1</td>
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">5.38</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">S24</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">6.49</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">645</td>
<td style="text-align: right;">172.0</td>
<td style="text-align: right;">52.5</td>
<td style="text-align: right;">9.43</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: right;">9.1</td>
<td style="text-align: right;">9.75</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">79.7</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.76</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S25</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">496</td>
<td style="text-align: right;">162.0</td>
<td style="text-align: right;">32.2</td>
<td style="text-align: right;">56.70</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.10</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">49.8</td>
<td style="text-align: right;">29.5</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">5.31</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">S26</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6.35</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">543</td>
<td style="text-align: right;">137.0</td>
<td style="text-align: right;">57.1</td>
<td style="text-align: right;">9.50</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">11.2</td>
<td style="text-align: right;">8.29</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">58.6</td>
<td style="text-align: right;">23.4</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">14.60</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S27</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6.48</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">558</td>
<td style="text-align: right;">140.0</td>
<td style="text-align: right;">54.5</td>
<td style="text-align: right;">9.10</td>
<td style="text-align: right;">4.34</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">8.19</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">57.0</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">3.05</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">6.73</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">S28</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">5.91</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">471</td>
<td style="text-align: right;">172.0</td>
<td style="text-align: right;">139.0</td>
<td style="text-align: right;">46.50</td>
<td style="text-align: right;">8.88</td>
<td style="text-align: right;">54.7</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: right;">12.5</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">6.32</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S29</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">6.57</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">492</td>
<td style="text-align: right;">121.0</td>
<td style="text-align: right;">122.0</td>
<td style="text-align: right;">26.40</td>
<td style="text-align: right;">7.79</td>
<td style="text-align: right;">18.8</td>
<td style="text-align: right;">9.63</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">33.3</td>
<td style="text-align: right;">22.1</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">5.25</td>
<td style="text-align: right;">2.74</td>
<td style="text-align: right;">1.81</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">S30</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">467</td>
<td style="text-align: right;">196.0</td>
<td style="text-align: right;">158.0</td>
<td style="text-align: right;">37.70</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">19.8</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">74.2</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S31</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5.25</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">400</td>
<td style="text-align: right;">89.0</td>
<td style="text-align: right;">101.0</td>
<td style="text-align: right;">18.40</td>
<td style="text-align: right;">9.98</td>
<td style="text-align: right;">22.6</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">26.3</td>
<td style="text-align: right;">32.6</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">S32</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">7.22</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">461</td>
<td style="text-align: right;">148.0</td>
<td style="text-align: right;">148.0</td>
<td style="text-align: right;">42.80</td>
<td style="text-align: right;">9.05</td>
<td style="text-align: right;">53.8</td>
<td style="text-align: right;">2.84</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">39.1</td>
<td style="text-align: right;">14.0</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: right;">2.51</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S33</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">5.14</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">492</td>
<td style="text-align: right;">166.0</td>
<td style="text-align: right;">117.0</td>
<td style="text-align: right;">22.80</td>
<td style="text-align: right;">5.26</td>
<td style="text-align: right;">28.5</td>
<td style="text-align: right;">3.59</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">87.4</td>
<td style="text-align: right;">21.8</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">S34</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">4.48</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">468</td>
<td style="text-align: right;">187.0</td>
<td style="text-align: right;">132.0</td>
<td style="text-align: right;">33.80</td>
<td style="text-align: right;">7.64</td>
<td style="text-align: right;">18.8</td>
<td style="text-align: right;">4.52</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">70.4</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S35</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">6.62</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">539</td>
<td style="text-align: right;">174.0</td>
<td style="text-align: right;">57.4</td>
<td style="text-align: right;">9.02</td>
<td style="text-align: right;">1.91</td>
<td style="text-align: right;">8.9</td>
<td style="text-align: right;">9.78</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">80.3</td>
<td style="text-align: right;">14.4</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">2.63</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">S36</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">683</td>
<td style="text-align: right;">175.0</td>
<td style="text-align: right;">64.8</td>
<td style="text-align: right;">7.04</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">6.57</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">62.0</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">5.24</td>
<td style="text-align: right;">2.19</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S37</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">464</td>
<td style="text-align: right;">131.0</td>
<td style="text-align: right;">66.0</td>
<td style="text-align: right;">7.51</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: right;">5.62</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">40.6</td>
<td style="text-align: right;">15.2</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">2.68</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: right;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">S38</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">2.33</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">656</td>
<td style="text-align: right;">165.0</td>
<td style="text-align: right;">125.0</td>
<td style="text-align: right;">201.00</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">24.8</td>
<td style="text-align: right;">15.70</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">151.0</td>
<td style="text-align: right;">79.1</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">8.97</td>
<td style="text-align: right;">3.95</td>
<td style="text-align: right;">2.34</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">2.20</td>
<td style="text-align: right;">0.42</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Using R, summary statistics (@sum-stat) were created from table 1 and initial observations were made. We found that concentrations for each element varied greatly in range and skew, where skew in this case is distance between mean and median.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics of Table 1</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">IQR</th>
<th style="text-align: right;">Kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cu</td>
<td style="text-align: right;">77.42</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: right;">74.00</td>
<td style="text-align: right;">77.00</td>
<td style="text-align: right;">80.75</td>
<td style="text-align: right;">90.00</td>
<td style="text-align: right;">6.75</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zn</td>
<td style="text-align: right;">20.95</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">22.00</td>
<td style="text-align: right;">28.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pb</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: right;">6.47</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: right;">4.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fe</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">2.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ni</td>
<td style="text-align: right;">525.05</td>
<td style="text-align: right;">69.56</td>
<td style="text-align: right;">400.00</td>
<td style="text-align: right;">468.75</td>
<td style="text-align: right;">520.00</td>
<td style="text-align: right;">558.75</td>
<td style="text-align: right;">683.00</td>
<td style="text-align: right;">90.00</td>
<td style="text-align: right;">2.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ag</td>
<td style="text-align: right;">149.07</td>
<td style="text-align: right;">29.59</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">132.50</td>
<td style="text-align: right;">157.00</td>
<td style="text-align: right;">171.00</td>
<td style="text-align: right;">199.00</td>
<td style="text-align: right;">38.50</td>
<td style="text-align: right;">2.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sb</td>
<td style="text-align: right;">105.16</td>
<td style="text-align: right;">82.28</td>
<td style="text-align: right;">32.20</td>
<td style="text-align: right;">61.42</td>
<td style="text-align: right;">101.00</td>
<td style="text-align: right;">120.75</td>
<td style="text-align: right;">549.00</td>
<td style="text-align: right;">59.33</td>
<td style="text-align: right;">23.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">As</td>
<td style="text-align: right;">36.81</td>
<td style="text-align: right;">51.35</td>
<td style="text-align: right;">7.04</td>
<td style="text-align: right;">10.16</td>
<td style="text-align: right;">20.25</td>
<td style="text-align: right;">37.38</td>
<td style="text-align: right;">211.00</td>
<td style="text-align: right;">27.21</td>
<td style="text-align: right;">9.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Co</td>
<td style="text-align: right;">5.23</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: right;">5.02</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">15.03</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">3.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cd</td>
<td style="text-align: right;">17.81</td>
<td style="text-align: right;">11.38</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">9.62</td>
<td style="text-align: right;">16.35</td>
<td style="text-align: right;">22.42</td>
<td style="text-align: right;">54.70</td>
<td style="text-align: right;">12.80</td>
<td style="text-align: right;">6.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sn</td>
<td style="text-align: right;">10.17</td>
<td style="text-align: right;">12.43</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">4.14</td>
<td style="text-align: right;">7.34</td>
<td style="text-align: right;">9.56</td>
<td style="text-align: right;">65.80</td>
<td style="text-align: right;">5.42</td>
<td style="text-align: right;">13.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Te</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">9.49</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bi</td>
<td style="text-align: right;">60.49</td>
<td style="text-align: right;">32.61</td>
<td style="text-align: right;">25.30</td>
<td style="text-align: right;">39.35</td>
<td style="text-align: right;">56.65</td>
<td style="text-align: right;">73.85</td>
<td style="text-align: right;">181.00</td>
<td style="text-align: right;">34.50</td>
<td style="text-align: right;">7.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mn</td>
<td style="text-align: right;">22.54</td>
<td style="text-align: right;">15.51</td>
<td style="text-align: right;">5.80</td>
<td style="text-align: right;">14.45</td>
<td style="text-align: right;">19.70</td>
<td style="text-align: right;">23.37</td>
<td style="text-align: right;">86.60</td>
<td style="text-align: right;">8.92</td>
<td style="text-align: right;">13.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">6.16</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">6.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">Al</td>
<td style="text-align: right;">6.57</td>
<td style="text-align: right;">4.29</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">3.34</td>
<td style="text-align: right;">5.28</td>
<td style="text-align: right;">8.77</td>
<td style="text-align: right;">21.20</td>
<td style="text-align: right;">5.43</td>
<td style="text-align: right;">4.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">V</td>
<td style="text-align: right;">2.23</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">2.68</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">5.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cr</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">5.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rb</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">6.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sr</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">3.51</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">2.01</td>
<td style="text-align: right;">15.10</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">7.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ba</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">4.59</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">11.17</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The elements Sb, As, Sn, Li, Sr, and Ba all show strong positive skews, numerous other elements show weaker skews. Cu and Zn are roughly symmetric. Ranges vary greatly with many magnitude differences between the ‘percentage based’ vs the ‘ppm’ elements (where percentage is ~10^4 more then ppm of the same value assuming the 2 measurement techniques are equally accurate) and between trace element ranges (Rb having a minimum of 0.03ppm while Ni has a maximum of 683ppm), and between the different samples vs same element (I.e. Sr has a minimum of 0.08ppm and a maximum of 15.10ppm which is over 180 times move than the minimum) these characteristics hint that a data transformation may be appropriate to increase interpretability.</p>
<p><span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> observed that samples S13, S25, and S38 were potential outliers due to various unusual element concentrations which we also noted. We also found that S22, S18, and S17 appear to have high Sr content (15.1ppm, 11.8ppm, 7.27ppm respectively, compared to a median of 0.42ppm) while S28, S22, and S19 have high Ba content (4.59ppm, 3.61ppm, 3.37ppm respectively, compared to a median of 0.28ppm).</p>
<p>Data clustering analysis may find that these groupings of samples cluster together in similar groups, furthering <span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span>, who claimed that trace element analysis could be used to differentiate providence of orichalcum alloy production.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/notchbox.png" class="img-fluid figure-img"></p>
<figcaption>Notch Boxplot</figcaption>
</figure>
</div>
<p>Ni (nickel) had the widest interquartile range of 90.00, indicating the greatest variation among the samples, while Sb (antimony) shows the largest total range, likely driven by sample 13’s recorded Sb being magnitudes larger than any of the other samples.</p>
<p>Due to the fact the data was recorded at different scales (percentage and PPM) and obvious outliers, log transformation and scaling were the next logical steps.</p>
<p><strong><em>3.1.1 Inconsistencies in Percentages</em></strong></p>
<p>The percentages of elements Cu, Zn, Pb, and Fe do not add up to 100% for each sample, as shown in the summary table below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary statistics for main component elements.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cu</td>
<td style="text-align: right;">77.42</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">77.00</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: right;">90.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zn</td>
<td style="text-align: right;">20.95</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">28.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pb</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">7.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fe</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">1.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">percentage_total</td>
<td style="text-align: right;">104.36</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">104.40</td>
<td style="text-align: right;">93.17</td>
<td style="text-align: right;">113.71</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Trace elements weren’t included for interpretability as the values are <span class="math inline">\(\times 10^{-4}\)</span> smaller.</p>
<p>These samples have a mean of 104.4% with a range 93.17% to 113.71%. Where 33 of the 38 samples exceed 100%. The most significant deviations are samples 8 and 38 (COMMENT ON THIS). <span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> attribute this to be due to errors generated from the low quantity of available material for sampling for each observation.</p>
<p>These samples have a mean of 104.4% with a range 93.17% to 113.71%. Where 33 of the 38 samples exceed 100%. The most significant deviations are samples 8 and 38 which have percentage totals of 112.44% and 113.71% respectively. <span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> attribute this to be due to errors generated from the low quantity of available material for sampling for each observation. For example, only 12.3 mg of sample 38 were obtained compared to the ideal 20mg of material as described in their methods.</p>
<p><strong>3.2 QQ-plots &amp; Henze-Zirkler Test For Multivariate Normality</strong></p>
<p>We first created and visually assessed the QQ-normal plots of table 1 to see if data transformation would be appropriate to manage potential outliers and standardisation issues.</p>
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/QQ_all.png" class="img-fluid"></p>
<p>As this was before there was any scaling performed, we opted to display the elements individually to better display each elements influence.</p>
<section id="primary-elements" class="level5">
<h5 class="anchored" data-anchor-id="primary-elements">Primary Elements</h5>
<p>Cu roughly follows the normal QQ-line, indicating it may follow a normal distribution. Fe and Pb are similarly distributed to Cu, but show slight deviation from QQ-line in the upper and lower tails. Zn has clear deviation from the QQ-line in the upper tail.</p>
</section>
<section id="trace-elements" class="level5">
<h5 class="anchored" data-anchor-id="trace-elements">Trace Elements</h5>
<p>Ag, Co, and Ni roughly follow the QQ-line indicating some evidence for normality. All other trace elements have blatant deviations from the normal line, particularly in the upper tail, likely due to previously discussed potential outliers. The relatively small sample size of 38, the tiny concentrations relative to the main elements, and the small amount of material taken/used for this material analysis technique are all 3 factors that could and likely would be influencing the data.</p>
</section>
<section id="data-transformation" class="level4">
<h4 class="anchored" data-anchor-id="data-transformation">Data Transformation</h4>
<p>We tried a simple log transformation witch resulted in a few zero values which was of some concern, as log(0) is undefined and can influence towards non-normality in multivariate data, particularly in small datasets like this one. We also had negative values. These were not an issue because we later chose metrics which are calculated from coordinate distances for clustering which can handle negative values.</p>
<p>Zero values were compensated for by instead transforming using log(<span class="math inline">\(\mathcal x\)</span> + 1), where <span class="math inline">\(\mathcal{x}\)</span> is our data.</p>
<p>Henze-Zirkler test established if there was preliminary evidence for multivariate normality.</p>
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/QQ_allnorm.png" class="img-fluid"></p>
<p>The QQ-plot of the log(<span class="math inline">\(\mathcal x\)</span> + 1) showed slight improvement overall. Multiple trace elements which had big upper skews now follow the theoretical line better with As, V, and Cr in particular following the theoretical line better.</p>
<p>There is still evidence of some elements not following assumptions of normality with Sr being the most prominent example, however, after the log(<span class="math inline">\(\mathcal x\)</span> + 1) transformation and considering the small sample size of the data set and most elements roughly following the line. We concluded that the assumption of normality would need further testing to evaluate, but appears to hold.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/notchboxnorm.png" class="img-fluid figure-img"></p>
<figcaption>Notch Boxplot</figcaption>
</figure>
</div>
<p>Ni (nickel) wen from widest to having an interquartile range smaller then the average, while Sb (antimony) went from largest range to again becoming much closer to the average. Overall we can clearly see that the standardisation and log(<span class="math inline">\(\mathcal x\)</span> + 1) transformation have greatly added in the interpretability of our EDA graphs. We note that Sr appears to have 4 unusual values/outliers.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Henze-Zirkler Test For Multivariate Normality</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">MVN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Henze-Zirkler</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: left;">asymptotic</td>
<td style="text-align: left;">✓ Normal</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The Henze-Zirkler test stipulates</p>
<p><span class="math display">\[
\begin{aligned}
\mathcal{H}_0 :&amp;
\text{ The data follow a multivariate normal distribution},
\\
\mathcal{H}_1 :&amp;
\text{ The data do not follow a multivariate normal distribution}.
\end{aligned}
\]</span></p>
<p>This generated a p-value=0.069, suggesting that there is insufficient evidence to reject that the data follow a multivariate normal distribution. However, the QQ-plot shows many variables with evidence of non-normality and/or significant outliers that we decided further testing was warranted before determining if multivariate normality is an appropriate statistical assumption.</p>
<p>Data manipulation by Median Absolute Deviation (MAD) was determined to be the next best step towards multivariate analysis.</p>
<p><strong>3.3 MAD</strong></p>
<p>MAD was used because it is a robust, outlier-resistant, measure of variability. The log(<span class="math inline">\(\mathcal x\)</span> +1) transformation somewhat fixed the skew and pulled the outliers in, but did not eliminate their mathematical influence. Interpreting variation in the data using the standard deviation which is highly affected by unusually high/low values or outliers would be statistically unsound.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Median Absolute Deviation Summary Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">Skewness</th>
<th style="text-align: right;">Kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ag</td>
<td style="text-align: right;">5.07</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">-1.13</td>
<td style="text-align: right;">3.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">Al</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">2.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">As</td>
<td style="text-align: right;">3.07</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">3.68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ba</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">2.63</td>
<td style="text-align: right;">8.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bi</td>
<td style="text-align: right;">4.06</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">2.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cd</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">2.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Co</td>
<td style="text-align: right;">1.81</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: right;">2.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cr</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">3.45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cu</td>
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">2.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fe</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">2.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">3.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mn</td>
<td style="text-align: right;">3.02</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">6.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ni</td>
<td style="text-align: right;">6.25</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">2.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pb</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">-2.34</td>
<td style="text-align: right;">9.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rb</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">5.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sb</td>
<td style="text-align: right;">4.62</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">5.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sn</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">1.12</td>
<td style="text-align: right;">4.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sr</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">1.26</td>
<td style="text-align: right;">3.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Te</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">6.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">V</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">3.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zn</td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">2.84</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From observed some massive deviations, as expected.</p>
<p>Variance because MAD&gt;SD robustness</p>
<p>Outliers MAD/median</p>
<p>Next the robust Z score was used to identify outliers that were candidates for removal. For our cutoff, we went with <span class="citation" data-cites="Leys2013-cr">Leys et al. (<a href="#ref-Leys2013-cr" role="doc-biblioref">2013</a>)</span> recommendation, who argued that the MAD is the most robust scale measure under contamination and recommend a median plus or minus 2.5 time MAD rule for outlier detection.</p>
<p>What is after we have “cleaned” up the outliers our |z| &gt; 2.5 rule removes samples 13, 25, and 38 which is exactly the sample ingots that Caponetti et al.&nbsp;set aside as their G4 group. Samples 7, 13 ,14 ,17, 19, 21, 22, and 28 were also removed using the same cut off.</p>
<p>{should probably explain why cutting out 11 samples will be good for the rest of our analysis, something along the line of outliers, terrible samples and low sample quality}.</p>
<p><strong>2.4 Multivariate normal distribution</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Henze_Zirkler Test Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test Statistic p.value     Method          MVN
1 Henze-Zirkler     1.001  &lt;0.001 asymptotic ✗ Not normal</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Henze_Zirkler Test Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test Statistic p.value     Method      MVN
1 Henze-Zirkler         1   0.055 asymptotic ✓ Normal</code></pre>
</div>
</div>
<p>Conducting the Henze Zirkler test for both the un-transformed data (p-value &lt;0.001) and the transformed data (p-value 0.055) we can reject the null hypotheses and conclude that the data is only not-normal when it is not-transformed and outliers remain. After log(<span class="math inline">\(\mathcal x\)</span> + 1) transformation and outlier removal using MAD, we can no longer safely reject the null hypotheses and have weak evidence (due to the p-value being barely above the cut off) that the processed data can be assumed to be multivariate normal.</p>
<p><strong>2.5 Correlation plots before and after</strong></p>
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/correlation_matrix.png" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/correlation_matrix_log.png" class="img-fluid figure-img"></p>
<figcaption>Correlation matrix of log-Transformed Data</figcaption>
</figure>
</div>
<p>Many of the element to element correlations change in degree and direction between the raw data and log(x + 1)-transformed data correlation matrices. Because Pearson correlations are not robust to changes due to outliers/heavily skewed data, we believe the transformed data correlation plot is a more accurate plot to make interpretations from.</p>
<p>Simple observations include a strong-positive correlation between Sb-As, Fe-Co, Ag-Bi, V-Cr, Cr-Rb, Cu-Bi, Cu-Ag, Sb-Cd, all of these pairs have an above 0.8 correlation value. Compared to the positive, strong-negative correlation can be found between Cd-Sn at ~-0.8 correlation value, with a multiple pairs having a somewhat strong-negative correlation in the negative 0.7 to -0.8 range. Interestingly the elements needed to create orichalchum/brass do not have strong correlations with one another.</p>
<p>This is a positive sign that the robustness of the transformation, i.e removing some of the outliers demonstrates their influence on the raw data.</p>
<p>Given the uncertainty about multivariate normality and the presence of negative values in our transformed data, a linear data analysis was chosen over a primary component analysis.</p>
</section>
</section>
<section id="lda" class="level2">
<h2 class="anchored" data-anchor-id="lda">4. LDA</h2>
<p><strong>4.1 PAM</strong></p>
<p>We started by performing a PAM (Partitioning Around Medoids) analysis</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top five cluster choices ranked by average silhouette width.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 21%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">k</th>
<th style="text-align: right;">Avg_Silhouette</th>
<th style="text-align: right;">Smallest_Cluster</th>
<th style="text-align: right;">Largest_Cluster</th>
<th style="text-align: left;">Cluster_Sizes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">6, 5, 15</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.182</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">7, 19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">6, 5, 4, 7, 4</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">5, 5, 3, 3, 7, 3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.170</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">5, 4, 2, 1, 3, 7, 3, 1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The silhouette value/metric is a measurement of the quality of a clustering. between -1 and 1. The data reports the optimal silhouette width as 5, with 0.6496032, indicating some. There are several other clustering values with a reported similar quality.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/PAM.png" class="img-fluid figure-img"></p>
<figcaption>PAM Silhouette Plot</figcaption>
</figure>
</div>
<p>Due to the ambiguous clustering, we opted to perform more cluster analyses to determine if this was a good fit.</p>
<p>MANHATTAN NOT EUCLEDIAN.</p>
</section>
<section id="linkage-analysis" class="level2">
<h2 class="anchored" data-anchor-id="linkage-analysis">5. Linkage Analysis</h2>
<p>Hierarchical cluster using Manhattan Distance as a measure. Chosen because it is more robust to outliers then Eucledian.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/dendrogram.png" class="img-fluid figure-img"></p>
<figcaption>Dendrogram</figcaption>
</figure>
</div>
<p>Cophenetic correlation coefficient ranges between -1 to 1, with a value of 1 indicating a perfect fit between the clusters and the data. A value of 0.798 means that the clustering is a fairly good fit. CCC can be used to compare between clustering methods.</p>
<p>We can see which sample pairs are more similar to one another, then to other sample pairs, for example samples 5 and 8 are more similar to one another then either is too the rest of the yellow cluster. We can also see for example that sample 32 is most similar to the grouping of samples 31, 3, 10, and 29 then to any of those samples individually.</p>
</section>
<section id="cluster-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cluster-analysis">6. Cluster Analysis</h2>
<section id="umap-projection" class="level5">
<h5 class="anchored" data-anchor-id="umap-projection"><strong>6.1 UMAP Projection</strong></h5>
<p>Given the low cophenetic correlation from the linkage analysis and the ambiguous silhouette width associated with the chosen k = 3 from the PAM analysis, we performed a UMAP projection to better visualise the clustering.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/UMAP.png" class="img-fluid figure-img"></p>
<figcaption>UMAP</figcaption>
</figure>
</div>
<p>The UMAP PAM projection shows clear overlap groupings.</p>
<p>Interesting to note samples 16 and 15 are in different clusters but are close together on the coordinate space when compared to the dendrogram above. This makes intuitive sense as these two samples have a moderate degree of similarity to one another but both also are only moderately similar to their assigned clusters. On a UMAP projection, distance between points within a cluster can be seen as conveying the points similarity with each other however comparing far away points/clusters to each other can lead to issues due to the universal distance not being directly scaled. UMAP projections arn’t ideal for making interpretations from but the visualisation of PAM clusters allows us to see that all 3 clusters are somewhat close to one another.</p>
<p><strong>6.2 Fuzzy Analysis</strong></p>
<p>As the fourth and final method of clustering, we performed a Fuzzy analysis.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Fuzzy K Silhouettes Clusterings</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Clus 1</th>
<th style="text-align: right;">Clus 2</th>
<th style="text-align: right;">Clus 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0.3642165</td>
<td style="text-align: right;">0.3205779</td>
<td style="text-align: right;">0.3152056</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0.4192879</td>
<td style="text-align: right;">0.3126837</td>
<td style="text-align: right;">0.2680284</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">0.3964731</td>
<td style="text-align: right;">0.3498160</td>
<td style="text-align: right;">0.2537109</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">0.3564183</td>
<td style="text-align: right;">0.2702156</td>
<td style="text-align: right;">0.3733661</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: right;">0.3731855</td>
<td style="text-align: right;">0.4223339</td>
<td style="text-align: right;">0.2044806</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: right;">0.3308487</td>
<td style="text-align: right;">0.3793640</td>
<td style="text-align: right;">0.2897873</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: right;">0.3972201</td>
<td style="text-align: right;">0.3416203</td>
<td style="text-align: right;">0.2611597</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: right;">0.5056657</td>
<td style="text-align: right;">0.1835340</td>
<td style="text-align: right;">0.3108003</td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: right;">0.3788758</td>
<td style="text-align: right;">0.2666590</td>
<td style="text-align: right;">0.3544652</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: right;">0.3814978</td>
<td style="text-align: right;">0.3462338</td>
<td style="text-align: right;">0.2722684</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: right;">0.3558813</td>
<td style="text-align: right;">0.3226723</td>
<td style="text-align: right;">0.3214464</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">23</td>
<td style="text-align: right;">0.4224857</td>
<td style="text-align: right;">0.3589670</td>
<td style="text-align: right;">0.2185473</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24</td>
<td style="text-align: right;">0.3166053</td>
<td style="text-align: right;">0.2376488</td>
<td style="text-align: right;">0.4457459</td>
</tr>
<tr class="even">
<td style="text-align: left;">26</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">27</td>
<td style="text-align: right;">0.3161169</td>
<td style="text-align: right;">0.2755752</td>
<td style="text-align: right;">0.4083079</td>
</tr>
<tr class="even">
<td style="text-align: left;">29</td>
<td style="text-align: right;">0.3857492</td>
<td style="text-align: right;">0.3469122</td>
<td style="text-align: right;">0.2673387</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30</td>
<td style="text-align: right;">0.3323539</td>
<td style="text-align: right;">0.3123218</td>
<td style="text-align: right;">0.3553243</td>
</tr>
<tr class="even">
<td style="text-align: left;">31</td>
<td style="text-align: right;">0.3341482</td>
<td style="text-align: right;">0.3798999</td>
<td style="text-align: right;">0.2859519</td>
</tr>
<tr class="odd">
<td style="text-align: left;">32</td>
<td style="text-align: right;">0.3863466</td>
<td style="text-align: right;">0.3057601</td>
<td style="text-align: right;">0.3078933</td>
</tr>
<tr class="even">
<td style="text-align: left;">33</td>
<td style="text-align: right;">0.3072383</td>
<td style="text-align: right;">0.3232066</td>
<td style="text-align: right;">0.3695551</td>
</tr>
<tr class="odd">
<td style="text-align: left;">34</td>
<td style="text-align: right;">0.3259026</td>
<td style="text-align: right;">0.2901749</td>
<td style="text-align: right;">0.3839225</td>
</tr>
<tr class="even">
<td style="text-align: left;">35</td>
<td style="text-align: right;">0.3335817</td>
<td style="text-align: right;">0.2356255</td>
<td style="text-align: right;">0.4307928</td>
</tr>
<tr class="odd">
<td style="text-align: left;">36</td>
<td style="text-align: right;">0.4045562</td>
<td style="text-align: right;">0.2967087</td>
<td style="text-align: right;">0.2987351</td>
</tr>
<tr class="even">
<td style="text-align: left;">37</td>
<td style="text-align: right;">0.3983628</td>
<td style="text-align: right;">0.2871473</td>
<td style="text-align: right;">0.3144899</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/Fuzzy.png" class="img-fluid figure-img"></p>
<figcaption>Fuzzy Membership Certainty</figcaption>
</figure>
</div>
<p>The graph of Fuzzy Membership Certainty shows that the majority of our observations are near ambiguous in there assigned groupings.</p>
<p>Picks by median centrality, determines closest group and percentage it belongs in said group.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">5. Results</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The default value alpha=1 has been set </code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Clustering Methods</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Clusters</th>
<th style="text-align: right;">Mean_Size</th>
<th style="text-align: right;">Max_size</th>
<th style="text-align: right;">Min_size</th>
<th style="text-align: right;">Avg.Silhouette</th>
<th style="text-align: right;">CCC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PAM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8.667</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hierarchical Clustering</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8.667</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.312</td>
<td style="text-align: right;">0.798</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UMAP + PAM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8.667</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.296</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fuzzy Analysis</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8.667</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/luke8471/STAT394-GROUP-3/main/Figures/ARI_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>ARI Heat Map</figcaption>
</figure>
</div>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section"></h4>
<p><span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> determined that the quantity of attained sample was attributed some to error generation. Both samples S38 and S08 had respective quantities 12.3mg and 16.0mg. The average amount of material sampled was reported at ~20mg.</p>
<p>The original study only had access to 38/40 ingots as they were on loan to another institute. This is an extension of that analysis, increasing the sample size at this point of the data analysis would inflate the false positive rate.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">6. Discussion</h2>
<p>It is difficult to make a direct comparison to the statistical multivariate analysis performed by <span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> due to the fact that their EDA is not available nor is there much mention to why they chose certain statistical techniques. In addition, they factored the physical characteristics of each ingot into their analysis.</p>
<p>Historically orichalcum identification has been difficult to confirm. Recorded identifications have left a lot to be desired with silver-like metals being called orichalcum, but after in-depth chemoanalysis was performed sometimes decades later, the metal would be determined to not have the hallmarks of orichalcum <span class="citation" data-cites="722f3324-e1f8-35af-a68a-e191baa52ba6">Caley (<a href="#ref-722f3324-e1f8-35af-a68a-e191baa52ba6" role="doc-biblioref">1967</a>)</span>. Due to rarity, historians have often had to rely on ancient texts with vague descriptions of orichalcum-like metals to try and map the history of ancient metallurgy.</p>
<p>This study boils down to these simple limitations.</p>
<center>
<p><em>A study on a sample group this large has never been done before.</em></p>
<p><em>Also, this dataset is not very large.</em></p>
</center>
<p>A study on a sample group this large has never been done before. Also, this dataset is not very large.</p>
<p>With so little to compare it to and</p>
<p>their motivation was to create a starting point for giving insight into archaeometric study of the orichalcum ingots regarding their origin and manufacture technologies.</p>
<p><span class="citation" data-cites="Caponetti2017-sc">Caponetti, Armetta, Martino, et al. (<a href="#ref-Caponetti2017-sc" role="doc-biblioref">2017</a>)</span> determined 3 distinct groupings of ingots, which provides evidence of a scarce and highly prized alloy being manufactured in one place at one time. This was determined with the added variable of the physical form of the ingots.</p>
<p>Our results</p>
<p>The find was dated to ~600BCE, the approximate age of the ship, and by the pottery also found in the wreck.</p>
<p>A study on a sample group this large has never been done before. Also, this dataset is not very large. - love this sentence 10/10.</p>
<p>XRF is a portable, non-invasive method of getting accurate readings within a certain range of elements (find that bit again). The ICP-OE and ICP-MS chemometric techniques require a small amount of material to be sacrificed in order to obtain a full range of the elemental composition of each ingot.</p>
<p><span class="citation" data-cites="Caponetti2017-fd">Caponetti, Armetta, Brusca, et al. (<a href="#ref-Caponetti2017-fd" role="doc-biblioref">2017</a>)</span> performed chemoanalysis to determine the trace elements of these orichalcum ingots. Using this data, they determined correlation between the observed different features and the composition to group the ingots into their appropriate cluster. This is an extension from a fledgling study by the same author, where they performed a less invasive XRF (X-Ray Fluorescence) spectroscopy of the ingots, a non-distructive test that can be performed in the field.</p>
<p>Our study also has the same motivations. We aim to provide a high level data analysis to provide a detailed, and logical, path to a linkage analysis.</p>
<p>Motivation, problem statement, approach, results, conclusions.</p>
<p>What were the limitations of this study?</p>
<p>What further research could be done? Different statistical analysis?</p>
<p>When working with museum quality pieces, that need destructive analyses performed to</p>
<p>We also took a preliminary look at the Copper (Cu), Zinc (Zn), Lead (Pb), and Tin (Sn) as they are the four alloying elements that are known to define orichalcum and historically have been the primary elemental components used to date and pinpoint origin of other orichalcum artifacts.</p>
</section>
<section id="refrences" class="level2">
<h2 class="anchored" data-anchor-id="refrences">7. Refrences</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Angelucci2026" class="csl-entry" role="listitem">
Angelucci, O. (2026). <em><span>T</span>he <span>S</span>unken <span>S</span>hip of <span>G</span>ela: <span>T</span>he <span>A</span>ncient <span>S</span>ecret of the <span>S</span>icilian <span>S</span>ea — medium.com</em>. <a href="https://medium.com/ash-and-devotion/the-sunken-ship-of-gela-the-ancient-secret-of-the-sicilian-sea-796f56d2dcc6" class="uri">https://medium.com/ash-and-devotion/the-sunken-ship-of-gela-the-ancient-secret-of-the-sicilian-sea-796f56d2dcc6</a>.
</div>
<div id="ref-722f3324-e1f8-35af-a68a-e191baa52ba6" class="csl-entry" role="listitem">
Caley, E. R. (1967). Investigations on the origin and manufacture of orichalcum. In <em>Archaeological chemistry: A symposium</em> (pp. 59–74). University of Pennsylvania Press. <a href="http://www.jstor.org/stable/j.ctv512vfn.7">http://www.jstor.org/stable/j.ctv512vfn.7</a>
</div>
<div id="ref-Caponetti2017-fd" class="csl-entry" role="listitem">
Caponetti, E., Armetta, F., Brusca, L., Chillura Martino, D., Saladino, M. L., Ridolfi, S., Chirco, G., Berrettoni, M., Conti, P., Bruno, N., &amp; Tusa, S. (2017). A multivariate approach to the study of orichalcum ingots from the underwater gela’s archaeological site. <em>Microchem. J.</em>, <em>135</em>, 163–170.
</div>
<div id="ref-Caponetti2017-sc" class="csl-entry" role="listitem">
Caponetti, E., Armetta, F., Martino, D. C., Saladino, M. L., Ridolfi, S., Chirco, G., Berrettoni, M., Conti, P., Bruno, N., &amp; Tusa, S. (2017). <em>First discovery of orichalcum ingots from the remains of a 6Th century <span>BC</span> shipwreck near gela (sicily) seabed</em>.
</div>
<div id="ref-Frery2020-ex" class="csl-entry" role="listitem">
Frery, A. C., Gomez, L., &amp; Medeiros, A. C. (2020). A badging system for reproducibility and replicability in remote sensing research. <em>IEEE J. Sel. Top. Appl. Earth Obs. Remote Sens.</em>, <em>13</em>, 4988–4995.
</div>
<div id="ref-Leys2013-cr" class="csl-entry" role="listitem">
Leys, C., Ley, C., Klein, O., Bernard, P., &amp; Licata, L. (2013). Detecting outliers: Do not use standard deviation around the mean, use absolute deviation around the median. <em>J. Exp. Soc. Psychol.</em>, <em>49</em>(4), 764–766.
</div>
<div id="ref-davidmathlogicColoringColorblindness" class="csl-entry" role="listitem">
Nichols, D. <em><span>C</span>oloring for <span>C</span>olorblindness — davidmathlogic.com</em>. <a href="https://davidmathlogic.com/colorblind/#%23{D}81{B}60-%231{E}88{E}5-%23{F}{F}{C}107-%23004{D}40-%2324e9fb" class="uri">https://davidmathlogic.com/colorblind/#%23{D}81{B}60-%231{E}88{E}5-%23{F}{F}{C}107-%23004{D}40-%2324e9fb</a>.
</div>
<div id="ref-nuttersworldGelaWreck" class="csl-entry" role="listitem">
Nutter, N. (2025). <em><span>G</span>ela 1 <span>W</span>reck: <span>A</span>rchaic <span>G</span>reek <span>S</span>hip <span>D</span>iscovery, <span>S</span>ewn-<span>P</span>lank <span>T</span>echnology &amp; <span>T</span>rade (500–480 <span>B</span><span>C</span>) — nuttersworld.com</em>. <a href="https://nuttersworld.com/iron-age-shipwrecks-mediterranean-sea/gela-1/" class="uri">https://nuttersworld.com/iron-age-shipwrecks-mediterranean-sea/gela-1/</a>.
</div>
<div id="ref-Seshu2023" class="csl-entry" role="listitem">
Vungarala, S. K. (2023). <em><span>P</span><span>C</span><span>A</span> vs <span>L</span><span>D</span><span>A</span> — <span>N</span>o more confusion! — seshu8hachi</em>. <a href="https://medium.com/@seshu8hachi/pca-vs-lda-no-more-confusion-fc21fb8d06e9" class="uri">https://medium.com/@seshu8hachi/pca-vs-lda-no-more-confusion-fc21fb8d06e9</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>