---
title: "La code - of ingots"
author: "Gaia Smith"
date: "2026-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages to load/install:
```{r packages, include=FALSE}

library(tabulapdf)
library(dplyr)
library(tidyr)
library(pdftools)
library(ggcorrplot)
library(mvtnorm)
library(GGally)


```

##  Reading the pdf:
```{r reading pdf, echo=TRUE}

#Heres how to load it you will have to write a path to where you keep the pdf on your computer:
ingots <- pdf_text("C:/Users/smith/Desktop/STAT394/Group Project/A multivariate approach to the study of orichalcum ingots from the underwater Gela's archaeological site.pdf")

#check you have all the pages
length(ingots) #should out put 8

#prints page 3 which has the table on:
cat(ingots[[3]])

#this works if we want to view the pdf! not extract the data

```

##  Extracting the table from the pdf:
```{r extracting the table, echo=TRUE}

ingots2 <- extract_tables("C:/Users/smith/OneDrive/Desktop/A multivariate approach to the study of orichalcum ingots from the underwater Gela's archaeological site.pdf", pages=3)

head(ingots2)

print(ingots2)

#lets store it in a table:

table1 <- ingots2[[1]]

#when I fist this this you couldn't view Ni, Ag and Sb separately they all went under concentration
View(table1)

```

##  Cleaning the table:
```{r cleaning the table, echo=TRUE}
table1 <- table1 %>%
  separate(
    `Concentration in PPM`,
    into = c("Ni", "Ag", "Sb"),
    sep = " "
  )

#how to check:
table1[1:3, ] |> 
  print(width = Inf)

#this should now have all the columns separate :)
View(table1)

#making sure all the columns are named correctly:
names(table1) <- c(
  "Sample", "Cu", "Zn", "Pb", "Fe",
  "Ni", "Ag", "Sb", "As", "Co", "Cd", "Sn",
  "Te", "Bi", "Mn", "Li", "Al", "V", "Cr",
  "Rb", "Sr", "Ba", "Cu_Zn"
)

View(table1)

Ingots.table<- table1[-1, ] #this just gets rid of the extra row of names so now we just have one, and renames our table

### at this point I noticed the data was all in a list rather then numeric so here's how to make it numeric:
Ingots.table <- sapply(Ingots.table, as.numeric)

View(Ingots.table)


```

typeof(Ingots.table)

##  Summary of the data:
```{r summary of table, echo=TRUE}
#summary of the table:
summary(Ingots.table)

```

##  Correlation table:
```{r correlation table}
cor(Ingots.table[,-1])
```

##  Correlation plot:
```{r correlation plot, echo=TRUE}
ggcorrplot(cor(Ingots.table[ ,-1]),
           method = "circle",
           hc.order = TRUE,
           type = "lower")

```

##  QQ-normal plots:
```{r qqnormal, echo=TRUE}

qqnorm(log(Ingots.table), col="blue")
qqline(log(Ingots.table), col="red")

```




##  Boxplot: (taking the log)
```{r boxplot, echo=TRUE}
boxplot(log(Ingots.table[,c(-1,-23)]), notch = TRUE, col="green")

boxplot(mad(Ingots.table))



```

##  looking closer at the at the correlation between V and CR:
```{r V and CR, echo=TRUE}
mu1 <- colMeans(Ingots.table[,18:19])
sigma1 <- var(Ingots.table[,18:19])

n <-38
x <- seq(mu1[1]-3*sqrt(sigma1[1,1]), mu1[1]+3*sqrt(sigma1[1,1]), len=n)
y <- seq(mu1[2]-3*sqrt(sigma1[2,2]), mu1[2]+3*sqrt(sigma1[2,2]), len=n)
xy <- expand.grid(x=x, y=x)
z <- dmvnorm(xy, mu1, sigma1)
V.and.CR <- matrix(z, nrow = n)
persp(x, y, V.and.CR)

```

## ggpairs:
```{r ggpairs, echo=TRUE}
ggpairs(cor(Ingots.table[,c(2:4,12)]))

```

